apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - crd
  - rbac
  - manager
  - certmanager
  - webhook
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
#- ../prometheus

namePrefix: sidero-

patchesStrategicMerge:
  # Protect the /metrics endpoint by putting it behind auth.
  # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
  - manager_auth_proxy_patch.yaml
  # If you want your controller-manager to expose the /metrics
  # endpoint w/o any authn/z, uncomment the following line and
  # comment manager_auth_proxy_patch.yaml.
  # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
  #- manager_prometheus_metrics_patch.yaml
  - manager_webhook_patch.yaml
  - webhookcainjection_patch.yaml
vars:
  - name: SIDERO_CERTIFICATE_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
  - name: SIDERO_SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: webhook-service

namespace: sidero-system
