apiVersion: v1
kind: Service
metadata:
  name: sidero-webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: sidero-controller-manager
