# The following patch adds a directive for certmanager to inject CA into the CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(SIDERO_CERTIFICATE_NAMESPACE)/$(SIDERO_CERTIFICATE_NAME)
  name: environments.metal.sidero.dev
